num_motion: 16
# foot : AL-8/14, AR-17/23, BL-26/32 , BR-35/41


motion0:
  foot: 41 #35 #BR
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion1:
  foot: 23 #17 #AR
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion2:
  foot: 32 # 26 #BL
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion3:
  foot: 14 #8 #AL
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

##
motion4:
  foot: 41 #35 #BR
  pos: [0,-0.1,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion5:
  foot: 23 #17 #AR
  pos: [0,-0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion6:
  foot: 32 # 26 #BL
  pos: [0,-0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion7:
  foot: 14 #8 #AL
  pos: [0,-0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

##
motion8:
  foot: 41 #35 #BR
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion9:
  foot: 23 #17 #AR
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion10:
  foot: 32 # 26 #BL
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion11:
  foot: 14 #8 #AL
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

##
motion12:
  foot: 41 #35 #BR
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion13:
  foot: 23 #17 #AR
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion14:
  foot: 32 # 26 #BL
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion15:
  foot: 14 #8 #AL
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true