num_motion: 4 #4
type_motion: 0 # 0:climbing, 1:walking, 2:balancing

# foot : AL-0, AR-1, BL-2, BR-3
# frame : base-0, foot-1

motion0:
  foot: 1
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.07
  durations: [0.5, 0.2, 2.0, 0.2]
  frame: 0

motion1:
  foot: 2
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.07
  durations: [0.5, 0.2, 2.0, 0.2]
  frame: 0

motion2:
  foot: 3
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.07
  durations: [0.5, 0.2, 2.0, 0.2]
  frame: 0

motion3:
  foot: 0
  pos: [0.1,0,0]
  ori: [1,0,0,0]
  swing_height: 0.07
  durations: [0.5, 0.2, 2.0, 0.2]
  frame: 0