num_motion: 8
# foot : AL-8/14, AR-17/23, BL-26/32 , BR-35/41
#
#              BR       BL 
#                \\____//
#                 /    \
#                | base |
#                 \____/
#                //    \\
#               AR      AL
#


motion0:
  foot: 14 #8 #AL
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  
  swing_height: 0.05
  b_relative: true


motion1:
  foot: 32 # 26 #BL
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion2:
  foot: 23 #17 #AR
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion3:
  foot: 41 #35 #BR
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true


motion5:
  foot: 23 #17 #AR
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion4:
  foot: 41 #35 #BR
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion6:
  foot: 14 #8 #AL
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion7:
  foot: 32 # 26 #BL
  pos: [0.15,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true
