num_motion: 56
# foot : AL-8/14, AR-17/23, BL-26/32 , BR-35/41
#
#              BR       BL 
#                \\____//
#                 /    \
#                | base |
#     -- y        \____/
#    |           //    \\
#    x          AR      AL
#


################ to center ################
motion0:
  foot: 32 # 26 #BL (1)
  pos: [0.05, -0.05,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion1:
  foot: 41 #35 #BR (2)
  pos: [0.05,0.05,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion2:
  foot: 23 #17 #AR
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion3:
  foot: 41 #35 #BR
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion4:
  foot: 32 # 26 #BL (1)
  pos: [0.1,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion5:
  foot: 23 #17 #AR (3)
  pos: [-0.1,-0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion6:
  foot: 32 # 26 #BL (1)
  pos: [-0.1,-0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true

motion7:
  foot: 23 #17 #AR (3)
  pos: [0.1,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.05
  b_relative: true
