num_motion: 18
# foot : A1 A2 A3  A4  A5  A6  A7  A8  A9
#         0 40 80 120 160 200 240 280 320

# [-0.1,0,0]
motion0:
  foot: 4 #_____A5
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion1:
  foot: 5 #_____A6
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion2:
  foot: 6 #_____A7
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion3:
  foot: 7 #_____A8
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion4:
  foot: 8 #_____A9
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion5:
  foot: 0 #_____A1
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion6:
  foot: 1 #_____A2
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion7:
  foot: 2 #_____A3
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion8:
  foot: 3 #_____A4
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true


###

# [0,0.1,0]
motion9:
  foot: 4 #_____A5
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion10:
  foot: 5 #_____A6
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion11:
  foot: 6 #_____A7
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion12:
  foot: 7 #_____A8
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion13:
  foot: 8 #_____A9
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion14:
  foot: 0 #_____A1
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion15:
  foot: 1 #_____A2
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion16:
  foot: 2 #_____A3
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion17:
  foot: 3 #_____A4
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

