num_motion: 18
# foot : A1 A2 A3  A4  A5  A6  A7  A8  A9
#         0 40 80 120 160 200 240 280 320

# [-0.1,0,0]
motion0:
  foot: 7 #__A8
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion1:
  foot: 8 #__A9
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion2:
  foot: 0 #__A1
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion3:
  foot: 1 #__A2
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion4:
  foot: 2 #__A3
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion5:
  foot: 3 #__A4
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion6:
  foot: 4 #__A5
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion7:
  foot: 5 #__A6
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion8:
  foot: 6 #__A7
  pos: [-0.1,0,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true


###

# [0,0.1,0]
motion9:
  foot: 7 #__A8
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion10:
  foot: 8 #__A9
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion11:
  foot: 0 #__A1
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion12:
  foot: 1 #__A2
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion13:
  foot: 2 #__A3
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion14:
  foot: 3 #__A4
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion15:
  foot: 4 #__A5
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion16:
  foot: 5 #__A6
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion17:
  foot: 6 #__A7
  pos: [0,0.1,0]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

