num_motion: 24
# foot : AL0 AR1 BL2 BR3 CL4 CR5
#        6   12  18  24  30  36

# [0.0500, -0.0866, 0.0000]
motion0:
  foot: 4 #120 #CL
  pos: [0.0500, -0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion1:
  foot: 2 #120 # BL
  pos: [0.0500, -0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion2:
  foot: 5 #120 #CR
  pos: [0.0500, -0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion3:
  foot: 0 #120 #AL
  pos: [0.0500, -0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion4:
  foot: 3 #120 #BR
  pos: [0.0500, -0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion5:
  foot: 1 #120 #AR
  pos: [0.0500, -0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

# [-0.0866, -0.0500, 0.0000]
motion6:
  foot: 4 #120 #CL
  pos: [-0.0866, -0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion7:
  foot: 2 #120 # BL
  pos: [-0.0866, -0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion8:
  foot: 5 #120 #CR
  pos: [-0.0866, -0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion9:
  foot: 0 #120 #AL
  pos: [-0.0866, -0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion10:
  foot: 3 #120 #BR
  pos: [-0.0866, -0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion11:
  foot: 1 #120 #AR
  pos: [-0.0866, -0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

##   pos: [-0.0500, 0.0866, 0.0000]
motion12:
  foot: 4 #120 #CL
  pos: [-0.0500, 0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion13:
  foot: 2 #120 # BL
  pos: [-0.0500, 0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion14:
  foot: 5 #120 #CR
  pos: [-0.0500, 0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion15:
  foot: 0 #120 #AL
  pos: [-0.0500, 0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion16:
  foot: 3 #120 #BR
  pos: [-0.0500, 0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion17:
  foot: 1 #120 #AR
  pos: [-0.0500, 0.0866, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

##[0.0866, 0.0500, 0.0000]
motion18:
  foot: 4 #120 #CL
  pos: [0.0866, 0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4  
  swing_height: 0.1
  b_relative: true

motion19:
  foot: 2 #120 # BL
  pos: [0.0866, 0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion20:
  foot: 5 #120 #CR
  pos: [0.0866, 0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion21:
  foot: 0 #120 #AL
  pos: [0.0866, 0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion22:
  foot: 3 #120 #BR
  pos: [0.0866, 0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true

motion23:
  foot: 1 #120 #AR
  pos: [0.0866, 0.0500, 0.0000]
  ori: [1,0,0,0]
  duration: 0.4
  swing_height: 0.1
  b_relative: true