servo_rate: 0.001 # !!this should be match with controller servo rate!!
is_record: false
show_joint_frame: false #false
show_link_frame: true #false
plot_mpc_result: false # true
plot_result: true # true

robot: robot_description/Robot/Magneto/MagnetoSim_Dart.urdf

#ground: robot_description/Ground/ground_terrain.urdf
#ground: robot_description/Ground/magneto/ground_climbing.urdf
#ground: robot_description/Ground/magneto/ground_inclined.urdf
#ground: robot_description/Ground/magneto/ground_inclined02.urdf
ground: robot_description/Ground/magneto/ground_inclined03.urdf
#ground: robot_description/Ground/magneto/ground_3d.urdf

initial_pose: [ 0.0, 0.0, 0.065, 0.0, 1.0, 0.0 ] # x,y,z, rx,ry,rz

control_configuration:
  kp: 20 #35 #20 #300
  kd: 3 #3 #3 #15
  torque_limit: 5 #4.5

magnetic_force: 147. #[N] 
residual_magnetism: 5.0 # 3.0 #[%]
friction: 0.7
