servo_rate: 0.001 # !!this should be match with controller servo rate!!
is_record: false
show_joint_frame: false #false
show_link_frame: false #false
plot_mpc_result: false # true
plot_result: true # true



robot: robot_description/Robot/magneto_files/MagnetoSim_Dart.urdf

# ground: robot_description/Ground/magneto/ground_plane.urdf
# initial_pose: [ 0.0, 0.0, 0.1, 0.0, 0.0, 0.0 ] # x,y,z, rz,ry,rx
# initial_pose: [ 0.0, 0.0, 0.1, 3.141592, 0.0, 0.0 ] # x,y,z, rz,ry,rx

### ground_inclined_1rad
# ground: robot_description/Ground/magneto/ground_inclined_1rad.urdf
# initial_pose: [ 0.0, 0.0, 0.15, 0.0, 1.0, 0.0 ] # x,y,z, rz,ry,rx
# initial_pose: [ 0.0, 0.0, 0.1, 0.0, 1.0, 0.0 ] # x,y,z, rz,ry,rx
# view_eye: [0.6, 3.5, 0.3] #5.14, 2.28, 3.0
# view_center: [0.2, 0.2, 0.3] #0.0, 0.2, 0.5
# view_up: [0.0, 0.0, 5.0] # 0.0, 0.0, 1.0

## ground_inclined_-1rad
# ground: robot_description/Ground/magneto/ground_inclined_m1rad.urdf
# initial_pose: [ 0.0, 0.0, 0.1, 0.0, -1.0, 0.0 ] # x,y,z, rz,ry,rx
# view_eye: [-0.6, 3.5, 0.3] #5.14, 2.28, 3.0
# view_center: [-0.2, 0.2, 0.3] #0.0, 0.2, 0.5
# view_up: [0.0, 0.0, 5.0] # 0.0, 0.0, 1.0

# ground_inclined_y1rad
# ground: robot_description/Ground/magneto/ground_inclined_r1rad.urdf
# initial_pose: [ 0.0, 0.0, 0.10, 0.0, 0.0, -1.0 ] # x,y,z, rz,ry,rx
# view_eye: [1.5, 5.5, 0.0] #5.14, 2.28, 3.0
# view_center: [0.2, 0.2, 0.3] #0.0, 0.2, 0.5
# view_up: [0.0, 0.0, 5.0] # 0.0, 0.0, 1.0

ground: robot_description/Ground/magneto/ground_inclined_intersection.urdf
# initial_pose: [ 0.0, -1.7, -0.30, 0.0, 0.0, -1.0 ] # x,y,z, rz,ry,rx
initial_pose: [ 0.8, -1.7, -0.30, 0.0, 0.0, -1.0 ] # x,y,z, rz,ry,rx
# initial_pose: [ 1.35, -1.1, -0.30, 0.0, -1.0, 0.0 ] # x,y,z, rz,ry,rx
# initial_pose: [ 1.35, -0.2, -0.30, 0.0, -1.0, 0.0 ] # x,y,z, rz,ry,rx

view_eye: [-1.5, 1.5, 0.5] #[-3.5, 5.0, 2.5]
view_center: [-0.5, 0.5, 0.3] #[0.0, 0.5, 1.0] 
view_up: [0.0, 0.0, 5.0] 

### ground_reversed
# ground: robot_description/Ground/magneto/ground_reversed.urdf
# initial_pose: [ 0.0, 0.0, -0.08, 0.0, -3.1415, 0.0 ] # x,y,z, rz,ry,rx

initial_rz: -90 #0 #90 #deg
motion_script: config/Magneto/MOTIONS/walkset_simple/walkset_square_180.yaml
# motion_script: config/Magneto/MOTIONS/walkset_simple/walkset_square.yaml

control_configuration:
  kp: 35 #100 #20 #300
  kd: 2 #10  #3 #15
  torque_limit: 5 #4.5

magnetic_force: 147. #[N] 
residual_magnetism: 5.0 # 3.0 #[%]
friction: 0.7
